
listColNum = ['weight',
              'Height',
              'SERUM_SODIUM',
              'SERUM_POTASSIUM',
              'SERUM_CREATININE',
              'SERUM_CALCIUM',
              'hemoglobin',
              'Phosphorous Test',
              'BLOOD SUGAR',
              'WBC',
              'UREA',
              'SERUM_ALBUMIN',
              'DIRECT_BILIRUBIN',
              'SGPT',
              'BILIRUBIN',
              'SGOT',
              'TOTAL_PROTEIN',
              'ALKALINE_PHOSPHATASE',
              'SERUM_GGT',
              'prothrombin',
              'Does Patient Have A Difficult Airway/Aspiration Risk?',
              'Does Patient Have A Risk of 500ml blood loss(7ml/kg in children)?',
              'Has antibiotic prophylaxis been given within the last 60 minutes?',
              'Has DVT prophylaxis been administered',
              'Is essential imaging displayed',
              'Has the imaging been discussed with radiologist preoperatively',
              'Gestational diabetes',
              'pulse', 'bp', 'urine output', 'urine',
              'intake', 'temp', 'stoma', 'rt', 'spo2',
              'PLT',
              'words']

list_to_avoid = ['weight', 'height', 'serum_sodium', 'serum_potassium', 'serum_creatinine', 'serum_calcium', 'hemoglobin', 'phosphorous test', 'wbc', 'urea', 'serum_albumin', 'direct_bilirubin', 'sgpt', 'bilirubin', 'sgot', 'total_protein', 'alkaline_phosphatase', 'serum_ggt', 'prothrombin', 'plt', 'blood sugar', 'is essential imaging displayed', 'has the imaging been discussed with radiologist preoperatively', 'words', 'pulse', 'urine output', 'urine', 'intake', 'temp', 'stoma', 'rt', 'spo2']
